### ISSUE TITLE
Probability must be <= 1 but was Infinity

### ISSUE THREAD

**Issue by jpzk** [optimaize/language-detector#24]
Exception in thread "Driver" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:162)
Caused by: java.lang.IllegalArgumentException: Probability must be <= 1 but was Infinity
	at com.optimaize.langdetect.DetectedLanguage.<init>(DetectedLanguage.java:47)
	at com.optimaize.langdetect.LanguageDetectorImpl.sortProbability(LanguageDetectorImpl.java:240)
	at com.optimaize.langdetect.LanguageDetectorImpl.getProbabilities(LanguageDetectorImpl.java:121)
	at com.optimaize.langdetect.LanguageDetectorImpl.detect(LanguageDetectorImpl.java:102)
	at

**Comment by fabiankessler** [comment]
Hrm. That's a bad one.

Do you have some userland code to reproduce this?

I quickly looked at the code based on your stack trace, and here are my findings:

The exception is thrown in DetectedLanguage line 47:

    public DetectedLanguage(@NotNull String language, double probability) {
        if (probability<0d) throw new IllegalArgumentException("Probability must be >= 0 but was "+probability);
        if (probability>1d) throw new IllegalArgumentException("Probability must be <= 1 but was "+probability);
        this.language = language;
        this.probability = probability;
    }

So what's happening is that the double value for probability comes in as "infinity". This is a special value Java uses for floating point primitives. Probably a result of a division by zero.

This could come from the Util.normalizeProb() method:

    /**
     * normalize probabilities and check convergence by the maximum probability
     * @return maximum of probabilities
     */
    public static double normalizeProb(double[] prob) {
        double maxp = 0, sump = 0;
        for(int i=0;i<prob.length;++i) sump += prob[i];
        for(int i=0;i<prob.length;++i) {
            double p = prob[i] / sump;
            if (maxp < p) maxp = p;
            prob[i] = p;
        }
        return maxp;
    }

Here we have a division by sump, which could possibly be zero.
This code is still the original from the original source, see http://grepcode.com/file/repo1.maven.org/maven2/com.optimaize.languagedetector/language-detector/0.4/com/cybozu/labs/langdetect/util/Util.java therefore I'm not familiar with it.

jpzk, can you set a break point in there and see what's going on? Maybe then, when looking at the variables, it becomes obvious to you what to do in case sump is zero.

**Comment by fabiankessler** [comment]
I'd really like to have this one closed for the next release. But it's a bit hard for me to analyze without being able to reproduce. jpzk can you, or can you give me info for how to reproduce?

**Comment by aecio** [comment]
I'm also having this bug, but it seems to be very hard to reproduce. I'm trying to create a test case, but it happens only occasionally and with multiple threads. It seems that this code is not thread safe.

**Comment by dennis97519** [comment]
Hi, I was able to produce it with the text:
"今回の強化詐欺騒動について俺は、他人事とまでは言わずとも、自分が具体的な損害をこうむることはあるまいと思っていた。鍛冶屋ネズハに剣を預けなければいいだけの話だ、と。"

I used the textObjectFactory and everything from the tutorial, so just follow the code there.

(From a Sword Art Online novel, haha. Reki don't go DMCA me for this :P)

Could you investigate how this is happening? Thanks.

**Comment by dennis97519** [comment]
Hi, I was able to reproduce it for a few times with the following text in a particular run for now:
"今回の強化詐欺騒動について俺は、他人事とまでは言わずとも、自分が具体的な損害をこうむることはあるまいと思っていた。鍛冶屋ネズハに剣を預けなければいいだけの話だ、と。"

I used the textObjectFactory and everything from the tutorial, so just follow the code there.

(From a Sword Art Online novel, haha. Reki don't go DMCA me for this :P)

Could you investigate how this is happening? Thanks.

PS:
Oh and the stack trace:
````java
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Probability must be <= 1 but was Infinity
	at com.optimaize.langdetect.DetectedLanguage.<init>(DetectedLanguage.java:46)
	at com.optimaize.langdetect.LanguageDetectorImpl.sortProbability(LanguageDetectorImpl.java:253)
	at com.optimaize.langdetect.LanguageDetectorImpl.getProbabilities(LanguageDetectorImpl.java:134)
	at com.optimaize.langdetect.LanguageDetectorImpl.detect(LanguageDetectorImpl.java:115)
	at (my GUI app here the line of code is Optional<LdLocale> lang = languageDetector.detect(textObject);)
````

Might be related to threading as well because I think the same bunch of text did not produce such error in a previous run. I'll try to get the values of the variables in the sources in the call stack... I think I'll just leave my application window open for now.

**Comment by dennis97519** [comment]
Yup this is really sporadic. Only encountered in that particular run. The exception did not occur is the subsequent runs. Is there anything inside that is affected by threading, system time or something?

**Comment by fabiankessler** [comment]
Did you have the seed parameter set? Probably not, this is probably where the randomness comes from. Can you try that? Then, if you hit a case where it happens, I expect it to be reproducible each time. See https://github.com/optimaize/language-detector/issues/14

**Comment by dennis97519** [comment]
I used everything from the examples... There is a default seed variable, and I don't know if any seed parameter is passed into the constructor of LanguageDetectorImpl. If not, the random function should be generating random numbers based on the default seed, because `Random rand = new Random(seed.or(DEFAULT_SEED));`

Anyway, that error only occurred constantly (every time I call the detect function) on that particular run, and never happened again on the subsequent runs.

**Comment by Bouki** [comment]
I'im facing the same issue (multi threaded environment and v0.5).
The issue seems completely random, I see it 1 run out of 50 on the exact same test.

**Comment by dennis97519** [comment]
Any idea on how to debug this issue?

**Comment by davireis** [comment]
Same here. Anything I can do to help nailing it?

**Comment by ChornHulio** [comment]
I run into the same problem. I'm in a multi-threaded environment with the old version 0.4. Now clue how to debug the error either...

**Comment by jakub-kudela** [comment]
Hi I have got the same issue, I have been calling the "detect" method while running map reduce on Hadoop over the CommonCrawl data set, which is about 2 000 000 000 web pages, for every <p> tag content. I had a method which in infinite loop tried to call the "detect" method until it succeeded (without the error that is described here) and to my surprise there has been even one detection that took 3 500 000 000 iterative subsequent calls of this method to return the Optional<LdLocale> without failing on this bug. I have made a file which contains 40000 paragraphs that failed to be detected within the 10000 iterations of "detect" method and I had tried the same thing locally in 20 threads simultaneously with single instance of "LanguageDetector" class. The error did not occur, I was not able to reproduce it. I have noticed that someone mentioned Spark, and in my case the Hadoop is problem, that might be a clue. I have also noticed that when I was creating Uber-jar with my mapreduce program I had to "shade" (with maven shade plugin) one dependency - google guava library (google commons) - because the Hadoop environment had replaced the guava with its own within the classpath. I must say your library is very very good in the ngram language detection thing, I am sorry about this bug. Hope that these clues will help. I am attaching the stacktrace below:

2015-11-21 21:01:32,488 ERROR [main] MapperImpl: Invalid WARC record!
java.lang.IllegalArgumentException: Probability must be <= 1 but was Infinity
        at com.optimaize.langdetect.DetectedLanguage.<init>(DetectedLanguage.java:46)
        at com.optimaize.langdetect.LanguageDetectorImpl.sortProbability(LanguageDetectorImpl.java:253)
        at com.optimaize.langdetect.LanguageDetectorImpl.getProbabilities(LanguageDetectorImpl.java:134)
        at com.optimaize.langdetect.LanguageDetectorImpl.detect(LanguageDetectorImpl.java:115)
        at MapperImpl.map(MapperImpl.java:113)
        at MapperImpl.map(MapperImpl.java:29)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at MapperImpl.run(MapperImpl.java:69)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

**Comment by jakub-kudela** [comment]
Hi I have copied the source of the project into mine Mapper and I have another batch of observations.

1.) All of mine detections called the "LanguageDetectorImpl.detectBlock" method cause all of the text I have inserted into the "LanguageDetectorImpl.detect" method were longer with length than the default "shortTextAlgorithm". 
2.) Now on the smaller subset of CommonCrawl I have made some logs and I have provided some sample [log_sample.txt](https://github.com/optimaize/language-detector/files/41093/log_sample.txt). As you can see the problem is that the "LanguageDetectorImpl.sortProbability" method gets from time to time an array which also contains NaN or Infinite double values (never negative Infinite). When it comes to calling of "DetectedLanguage.<init>" with these Infinite doubles it hits the exception (NaNs should not be the problem as they are not greater than treshold, i mean it is fact that Double.POSITIVE_INFINITY > 1, but is not true that Double.NaN < 1, also it is not true that Double.NaN > 1). The origin of these Infinite doubles comes for sure from the "LanguageDetectorImpl.detectBlockLongText" method, that is all I can say for this moment.
3.) The strange thing is the distribution of the Locales (languages) for which it hits the error in the method "DetectedLanguage.<init>". From the file that I am providing right now 
[lng_distribution.txt](https://github.com/optimaize/language-detector/files/41096/lng_distribution.txt) you can see that the language distribution is not even. Most of the time it happens for the Hindi, Maltese, Albanian and Swahili languages. I happen to speak fluently czech and I ran through all of the 133 occurences of these Infinite probablities of czech (cs) languages and none of the the input text contained czech. Not even a word. 
4.) From the empirical experiment I have mentioned in the third point I have augumented the "LanguageDetectorImpl.sortProbability" method so that I have changed the condition line "if (p >= probabilityThreshold) {" for "if (!Double.isInfinite(p) && p >= probabilityThreshold) {" and everything worked for me. However cannot tell this is semantically correct.

Sorry for not markdowning, I am not good at this. Hope that this helps.

**Comment by jakub-kudela** [comment]
Now I think that I have managed to find the exact line that makes this exception finally. Sorry for 3 separate comments but now I believe I have found the reason why this is happening. Look how I have decorated :) the "LanguageDetectorImpl.detectBlockLongText" method so that I could then in logs find the input and outputs of the arithmetic operation that seemed to me very suspicious. The line I am talking about is commented with "INCRIMINATING LINE:".

```java
private double[] detectBlockLongText(List<String> ngrams) {
    assert !ngrams.isEmpty();
    double[] langprob = new double[ngramFrequencyData.getLanguageList().size()];
    Random rand = new Random(seed.or(DEFAULT_SEED));
    for (int t = 0; t < N_TRIAL; ++t) {
        double[] prob = initProbability();
        double alpha = this.alpha + (rand.nextGaussian() * ALPHA_WIDTH);

        for (int i=0; i<ITERATION_LIMIT; i++) {
            int r = rand.nextInt(ngrams.size());
            updateLangProb(prob, ngrams.get(r), 1, alpha);
            
            if (i % 5 == 0) {
            	double norm = Util.normalizeProb(prob);
                if (norm > CONV_THRESHOLD) break; //this looks like an optimization to return quickly when sure. TODO document what's the plan.
            }
        }
        
        // START LOGGING
        String before = "abcdef before: langprob=" + Arrays.toString(langprob) + "; prob=" + Arrays.toString(prob);
        boolean beforeContainsInfinity = false;
        for (double p : langprob) { if (Double.isInfinite(p)) beforeContainsInfinity = true; }
        // END LOGGING
        
        // INCRIMINATING LINE:
        for(int j=0;j<langprob.length;++j) langprob[j] += prob[j] / N_TRIAL;
        
        // START LOGGING
        String after = "abcdef after: langprob=" + Arrays.toString(langprob);
        boolean afterContainsInfinity = false;
        for (double p : langprob) { if (Double.isInfinite(p)) afterContainsInfinity = true; }

        if (!beforeContainsInfinity && afterContainsInfinity) {
        	LOG.error(before);
        	LOG.error(after);
        }
        // END LOGGING
    }
    return langprob;
}
```

Now I have collected the logs and separated before-after pairs by newline. Now I have many of these pairs (the file is 250000 lines long) but I am providing just a sample of first 50 pairs. There you can see the arithmetic thing that makes these NaN and the Infinities which then produce these exceptions. 

[arithmetic_thing_log_sample.txt](https://github.com/optimaize/language-detector/files/41116/arithmetic_thing_log_sample.txt)

Now after this I have tried to enclose with logging (similarly as to the example above) all of the other probability arrays operations that are contained in the method "detectBlockLongText". And I have found that none other operation makes these Infinities. I believe that this is the sole moment that produces such values. Now I really hope that you can close this issue with these facts :).

**Comment by Bouki** [comment]
Have you tried to dump prob[j] and N_TRIAL ?
Because either N_TRIAL equals 0 (probably not the case) or initProbability/updateLangProb generate Inifinite values

**Comment by jakub-kudela** [comment]
N_TRIAL does not really matter. As you can see in the "LanguageDetectorImpl" source.

```java
private static final int N_TRIAL = 7;
```

I have said that I have enclosed all of the double-array operations (also calls of the submethods) within the method mentioned above and I have found that the infinite values are being created only by this line, no other:

```java
 for(int j=0;j<langprob.length;++j) langprob[j] += prob[j] / N_TRIAL;
```

Have you looked into the logs I have attached? I mean the [arithmetic_thing_log_sample.txt](https://github.com/optimaize/language-detector/files/41116/arithmetic_thing_log_sample.txt)

**Comment by lababidi** [comment]
I did my own testing and found that there is some sort of race condition. When I simplify the code for initProbability to only create a new Array of naive probabilities, I don't see the Infinity issue. See below:
```
double[] prob = new double[ngramFrequencyData.getLanguageList().size()];
for(int i=0;i<prob.length;++i) prob[i] = 1.0 / ngramFrequencyData.getLanguageList().size();
return prob;
```

**Comment by lababidi** [comment]
I found that changing initProbability to the below, the Infinity seems to go away. Any thoughts?
```
double[] prob = new double[ngramFrequencyData.getLanguageList().size()];
for(int i=0;i<prob.length;++i) prob[i] = 1.0 / ngramFrequencyData.getLanguageList().size();
return prob;
```

**Comment by lababidi** [comment]
I believe there is a race condition somewhere in the code. Could the devs please let me know if any Threading code is written in Language-Detection?

**Comment by jakub-kudela** [comment]
As lababidi suggested, I have tried to change the `LanguageDetectorImpl.initProbability()` method to following (without touching anything else in the original 0.5 code):

```java
private double[] initProbability() {
	/* Note: Original implementation is commented below.

    double[] prob = new double[ngramFrequencyData.getLanguageList().size()];
    if (priorMap != null) {
        System.arraycopy(priorMap, 0, prob, 0, prob.length);
        for(int i=0;i<prob.length;++i) prob[i] = priorMap[i];
    } else {
        for(int i=0;i<prob.length;++i) prob[i] = 1.0 / ngramFrequencyData.getLanguageList().size();
    }
    return prob;
	
	*/
	
	double[] prob = new double[ngramFrequencyData.getLanguageList().size()];
	for(int i=0;i<prob.length;++i) prob[i] = 1.0 / ngramFrequencyData.getLanguageList().size();
	return prob;
}
```

And everything worked well without any exception! Good one, but is this semantically correct?

**Comment by lababidi** [comment]
@jakub-kudela I basically ignored the `initProbability()` and wrote the `detect` methods as the following example to maintain the behavior. (`langListSize=ngramFrequencyData.getLanguageList().size()`):
```
    private double[] detectBlockShortText(Map<String, Integer> ngrams) {
        double[] prob = new double[langListSize];
        for(int i=0;i<prob.length;++i) prob[i] = 1.0 / langListSize;
        if(priorMap!=null)
            System.arraycopy(priorMap, 0, prob, 0, prob.length);

        for (Map.Entry<String, Integer> gramWithCount : ngrams.entrySet()) {
            updateLangProb(prob, gramWithCount.getKey(), gramWithCount.getValue());
        }
        Util.normalizeProb(prob);
        if (logger.isDebugEnabled()) logger.debug("==> " + sortProbability(prob));
        return prob;
    }
```

**Comment by jakub-kudela** [comment]
Nice work @lababidi  :+1: !

**Comment by RuedigerMoeller** [comment]
same issue here. It sometimes works for hours, then suddenly stops working giving this error. Even instantiating a new detector won't help ..

**Comment by dennis97519** [comment]
@lababidi So how do you recreate the exception in the original code? Under what condition does the exception occur?

**Comment by RuedigerMoeller** [comment]
I've got a web crawler. The error occurs after running it for some time (2-80 hours). So it seems like some files just create an invalid internal state. I have synchronized it with no success (so its probably not concurrency related)
